#!/bin/bash
                     os_usr_bin=/usr/bin
                       mlnx_bin=/opt/mellanox/bin
  mlnx_sf_mellanox_config_tools=mellanox-config-tools
{
  [ -f ${os_usr_bin}/${mlnx_sf_mellanox_config_tools} -o \
    -L ${os_usr_bin}/${mlnx_sf_mellanox_config_tools} ] && \
      rm -f ${os_usr_bin}/${mlnx_sf_mellanox_config_tools}

  ln -s ${mlnx_bin}/${mlnx_sf_mellanox_config_tools} \
    ${os_usr_bin}/${mlnx_sf_mellanox_config_tools}
} > /dev/null 2>&1
